# Generated by Django 6.1.1 on 2026-09-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('confirm_order', 'Can confirm orders'), ('cancel_order', 'Can cancel draft orders')]},
        ),
    ]
