# Generated by Django 6.1.1 on 2026-09-07 18:22

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balance', to='catalog.product')),
            ],
            options={
                'ordering': ['product__name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_balance_quantity_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('quantity_delta', models.IntegerField()),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='inventory_movement_delta_not_zero'), models.CheckConstraint(condition=models.Q(('quantity_before__gte', 0)), name='inventory_movement_before_gte_0'), models.CheckConstraint(condition=models.Q(('quantity_after__gte', 0)), name='inventory_movement_after_gte_0'), models.CheckConstraint(condition=models.Q(('quantity_after', django.db.models.expressions.CombinedExpression(models.F('quantity_before'), '+', models.F('quantity_delta')))), name='inventory_movement_balance_consistent')],
            },
        ),
    ]
