# Generated by Django 6.1.1 on 2026-09-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'permissions': [('manage_stock', 'Can register and adjust stock')]},
        ),
    ]
